# Generated by Django 5.2.2 on 2025-06-07 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('date', models.DateTimeField(verbose_name='Data de Criacao')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nome do Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preco do Produto')),
                ('stoque', models.IntegerField(verbose_name='Quantidade')),
                ('slug', models.SlugField(default=None, editable=False)),
                ('date_entry', models.DateTimeField(verbose_name='Data de entrada')),
                ('date_valid', models.DateField(verbose_name='Data De exporacao')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
