# Generated by Django 5.2.2 on 2025-06-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_client_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
