# Generated by Django 5.2.2 on 2025-06-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_selling_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
