# Generated by Django 5.2.2 on 2025-06-10 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_selling_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estato'),
        ),
        migrations.AlterField(
            model_name='selling',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.client'),
        ),
        migrations.AlterField(
            model_name='selling',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
