# Generated by Django 5.2.2 on 2025-06-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.FileField(upload_to='profile', verbose_name='Foto de Perfil')),
                ('address', models.CharField(max_length=300, verbose_name='Endereco')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('bi', models.CharField(max_length=100, verbose_name='Numero Do BI')),
                ('about', models.TextField(max_length=500, verbose_name='Sobre')),
            ],
        ),
    ]
